name: Force rebuild
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: touch index.html
      - run: echo "<!-- rebuild $(date) -->" >> index.html
